/* generated ELC source file - do not edit */
#include "r_elc_api.h"
const elc_cfg_t g_elc_cfg =
{ .link[ELC_PERIPHERAL_MTU0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_MTU3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_MTU4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_LLPPGPT_A] = ELC_EVENT_IOPORT_SINGLE0, /* IOPORT_SINGLE0 (Input edge detection of single input port 0) */
  .link[ELC_PERIPHERAL_LLPPGPT_B] = ELC_EVENT_IOPORT_SINGLE0, /* IOPORT_SINGLE0 (Input edge detection of single input port 0) */
  .link[ELC_PERIPHERAL_LLPPGPT_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_LLPPGPT_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_LLPPGPT_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_LLPPGPT_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_LLPPGPT_G] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_LLPPGPT_H] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_NONSAFTYGPT_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_NONSAFTYGPT_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_NONSAFTYGPT_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_NONSAFTYGPT_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_NONSAFTYGPT_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_NONSAFTYGPT_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_NONSAFTYGPT_G] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_NONSAFTYGPT_H] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC0_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC0_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC1_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC1_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CDCNT0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CDCNT0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ESC0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ESC1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GMA0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GMA1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_OUTPORTGR1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_OUTPORTGR2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_INPORTGR1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_INPORTGR2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_SINGLEPORT0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_SINGLEPORT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_SINGLEPORT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_SINGLEPORT3] = ELC_EVENT_NONE, /* No allocation */
};
