/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : rx565neddfp_i2c_slave.c
*  Description  : Main Program
*  Creation Date: 2026-08-19
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "r_riic_rx_if.h"
#include "r_riic_rx_config.h"
#include "r_riic_rx_pin_config.h"
#include "rx_fit_i2c_slave.h"
/*****************************************************************************
* Global definition
******************************************************************************/
//#define printf(...) ((void)0)

#define SLAVE_ADDR                  ((void *)0x4A)
static void salve_callback(void);    /* Slave transfer Callback function */
static riic_info_t iic_info_s = {0}; /* handler of RIIC Transfer */
static volatile bool is_slave_send = false;

void main(void);

extern volatile uint8_t  g_sci5_tx_end;
void my_sw_charput_function(char output_char)
{
	R_Config_SCI5_Serial_Send((uint8_t *)&output_char, 1);
	while(g_sci5_tx_end == false);
	g_sci5_tx_end = false;
}
/* Event callback - called from main loop when transfer completes */
static void on_i2c_event(rx_fit_i2c_slave_event_t event)
{
	uint8_t *rx = rx_fit_i2c_slave_get_rx_buf();
    uint8_t *tx = rx_fit_i2c_slave_get_tx_buf();

    if (event == RX_FIT_I2C_SLAVE_EVT_WRITE)
    {
        /* Master wrote data to us - parse command */
        printf("RX: %02x %02x %02x %02x %02x\n",
               rx[0], rx[1], rx[2], rx[3], rx[4]);

        /* Prepare response for next master read */
        tx[0] = rx[0] + 1;
        tx[1] = rx[1] + 1;
    }
    else
    {
        /* Master read data from us - update for next read */
        printf("TX: %02x %02x %02x %02x %02x\n",
               tx[0], tx[1], tx[2], tx[3], tx[4]);
        tx[4] += 1;
    }
}
/*******************************************************************************
* Function Name: main
* Description  : main function of riic slavemode
* Arguments    :
* Return Value :
*******************************************************************************/
void main(void)
{
	R_Config_SCI5_Start();
	printf("helloworld\n", 11);

	char fitVer[] = "RIIC Multi Master I2C Driver | rriicrx | Firmware Integration Technology | 3.11\n";
	printf("%s", fitVer);

	/* Init I2C slave with address 0x4A and event callback */
	rx_fit_i2c_slave_init(on_i2c_event);

	while (1)
	{
		rx_fit_i2c_slave_process();   /* Non-blocking, call every loop iteration */
		/* ... other tasks ... */
	}

}
/*******************************************************************************
End of function main
*******************************************************************************/

/*******************************************************************************
* Function Name: salve_callback
* Description  : callback function function of riic slavemode
* Arguments    :
* Return Value :
*******************************************************************************/
static void salve_callback(void)
{
    volatile riic_return_t ret;
    riic_mcu_status_t iic_status;

    ret = R_RIIC_GetStatus(&iic_info_s,&iic_status);

    if(RIIC_SUCCESS != ret)
    {
        //printf("Get I2c Status failed\n");
    }
    else
    {
        //printf("Get i2c status success,iic_status.LONG = %x\n",iic_status.LONG);
    }

    return;
}
/*******************************************************************************
End of function salve_callback
*******************************************************************************/
