/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : rx23e_i2c_slave.c
*  Description  : Main Program
*  Creation Date: 2026-08-19
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "Config_RIIC0.h"

void main(void);

/* Shared buffers - used by both main and ISR callbacks */
volatile uint8_t g_slave_rx_buf[5];
volatile uint8_t g_slave_tx_buf[5] = {0x00, 0x11, 0x22, 0x33, 0x44};

/* Event flags - set by ISR callbacks, read/cleared by main loop */
volatile uint8_t g_rx_done = 0;
volatile uint8_t g_tx_done = 0;

extern volatile uint8_t  g_sci5_tx_end;
void my_sw_charput_function(char output_char)
{
	R_Config_SCI5_Serial_Send((uint8_t *)&output_char, 1);
	while(g_sci5_tx_end == false);
	g_sci5_tx_end = false;
}

void main(void)
{
	R_Config_SCI5_Start();
	printf("helloworld\n", 11);

	char CGVer[] = "SCI/SCIF Asynchronous Mode | Code Generator | 1.12.0\n";
	printf("%s", CGVer);

	R_Config_RIIC0_Start();

	/* Start: arm for receive, waiting for master write */
	R_Config_RIIC0_Slave_Receive((uint8_t *)g_slave_rx_buf, 5);

	while(1)
	{
		if (g_rx_done)
		{
			g_rx_done = 0;

			printf("RX: %02x %02x %02x %02x %02x\n",
			       g_slave_rx_buf[0], g_slave_rx_buf[1], g_slave_rx_buf[2],
			       g_slave_rx_buf[3], g_slave_rx_buf[4]);

			/* Prepare tx data based on rx */
			g_slave_tx_buf[4] += 1;

			/* After write, arm for send (prepare for master read) */
			R_Config_RIIC0_Slave_Send((uint8_t *)g_slave_tx_buf, 5);
		}

		if (g_tx_done)
		{
			g_tx_done = 0;

			printf("TX: %02x %02x %02x %02x %02x\n",
			       g_slave_tx_buf[0], g_slave_tx_buf[1], g_slave_tx_buf[2],
			       g_slave_tx_buf[3], g_slave_tx_buf[4]);

			/* After read, arm for receive (prepare for next write) */
			R_Config_RIIC0_Slave_Receive((uint8_t *)g_slave_rx_buf, 5);
		}
	}
}
