/* generated configuration header file - do not edit */
#ifndef R_ETHER_PHY_CFG_H_
#define R_ETHER_PHY_CFG_H_
#define ETHER_PHY_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define ETHER_PHY_CHIP_DEFAULT  BOARD_PHY_TYPE
#define ETHER_PHY_CFG_PHY_LSI  (ETHER_PHY_CHIP_DEFAULT | ETHER_PHY_CHIP_VSC8541 | ETHER_PHY_CHIP_KSZ9131 | ETHER_PHY_CHIP_KSZ9031 | ETHER_PHY_CHIP_KSZ8081 | ETHER_PHY_CHIP_KSZ8041 |  0)
#endif /* R_ETHER_PHY_CFG_H_ */
